name: deis-monitor
from:
  name: deis-monitor
  version: 0.1.0
home: http://github.com/deis/monitor
version: 0.1.0
description: Provides a complete monitoring stack for kubernetes and deis.
maintainers:
- Jonathan Chauncey <jchauncey@deis.com>
details: |-
  NOTE: This chart requires daemonsets to be enabled. Please see https://github.com/kubernetes/kubernetes/blob/master/docs/api.md#enabling-resources-in-the-extensions-group for more information.

  This chart start will start the following components: InfluxDB, Telgraf, and Grafana 3. Each provides an integral part of the monitoring and alerting stack for deis and kubernetes. You can read more about each at https://github.com/deisthree/monitor.
